import type { NextPage, NextPageContext } from 'next';
import { getSession } from 'next-auth/react';
import { Session } from 'next-auth';
import Head from 'next/head';
import { useRouter } from 'next/router';

const Home: NextPage<{
    session: Session;
}> = ({ session }) => {
    console.log(session);

    return (
        <div>
            <Head>
                <title>Create Next App</title>
                <meta
                    content="Generated by create next app"
                    name="description"
                />
                <link href="/favicon.ico" rel="icon" />
            </Head>
            <main>
                <h1>Welcome to Insta Share</h1>
            </main>
        </div>
    );
};

export async function getServerSideProps(context: NextPageContext) {
    const session = await getSession(context);

    if (!session) {
        return {
            redirect: {
                destination: '/login',
                permanent: false,
            },
        };
    }

    return {
        props: { session },
    };
}

export default Home;
